// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TourPlanner.DataLayer.Data;

#nullable disable

namespace TourPlanner.Migrations
{
    [DbContext(typeof(TourPlannerDbContext))]
    partial class TourPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TourPlanner.BusinessLayer.Models.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TourPlanner.BusinessLayer.Models.TourAttributes", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("ChildFriendliness")
                        .HasColumnType("boolean");

                    b.Property<double>("Popularity")
                        .HasColumnType("double precision");

                    b.Property<double>("SearchAlgorithmRanking")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TourAttributes");
                });

            modelBuilder.Entity("TourPlanner.BusinessLayer.Models.TourDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("EstimatedTime")
                        .HasColumnType("interval");

                    b.Property<string>("RouteInformation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TourDetails");
                });

            modelBuilder.Entity("TourPlanner.BusinessLayer.Models.TourLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalDistance")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourLogs");
                });

            modelBuilder.Entity("TourPlanner.BusinessLayer.Models.TourAttributes", b =>
                {
                    b.HasOne("TourPlanner.BusinessLayer.Models.Tour", null)
                        .WithOne("TourAttributes")
                        .HasForeignKey("TourPlanner.BusinessLayer.Models.TourAttributes", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourPlanner.BusinessLayer.Models.TourDetails", b =>
                {
                    b.HasOne("TourPlanner.BusinessLayer.Models.Tour", null)
                        .WithOne("TourDetails")
                        .HasForeignKey("TourPlanner.BusinessLayer.Models.TourDetails", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourPlanner.BusinessLayer.Models.TourLog", b =>
                {
                    b.HasOne("TourPlanner.BusinessLayer.Models.Tour", "Tour")
                        .WithMany("TourLogs")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourPlanner.BusinessLayer.Models.Tour", b =>
                {
                    b.Navigation("TourAttributes");

                    b.Navigation("TourDetails");

                    b.Navigation("TourLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
